<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Keluar</name>
   <tag></tag>
   <elementGuidId>254ad249-d081-4e43-9110-3d22d579139b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.DropdownStyle__DropdownItemWrapper-sc-1sc3c6h-4.hRQwvs.active > div.UserMenuComponentssc__DropdownWrapper-sc-16frqer-3.iHpuAM > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div[2]/div/div/div[4]/nav/div[5]/div[3]/div/div/div/div/ul/li[5]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f2216906-b032-46c8-bf5c-8a6030861f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar</value>
      <webElementGuid>ea64ff4f-0c1e-45eb-8a66-6cb4b55c12cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;NavigationComponentssc__DrawerContainer-sc-vokz7d-0 daViyw&quot;]/div[@class=&quot;MainContainersc__MainLayout-sc-iy5ixg-0 llLQXs&quot;]/div[@class=&quot;MainContainersc__MainHeader-sc-iy5ixg-1 hiOHmW&quot;]/div[@class=&quot;GlintsContainer-sc-ap1z3q-0 iUnyrV max-height&quot;]/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-desktopS&quot;]/nav[@class=&quot;DesktopMenuComponentssc__Container-sc-wdt612-0 bFGUem&quot;]/div[@class=&quot;DesktopMenuComponentssc__RightMenuContainer-sc-wdt612-3 bSbWdk&quot;]/div[@class=&quot;DesktopMenuComponentssc__UserMenuItem-sc-wdt612-6 hJQYSk&quot;]/div[@class=&quot;UserMenuComponentssc__UserMenuContainer-sc-16frqer-0 qSCQQ&quot;]/div[@class=&quot;UserMenuComponentssc__UserSettingSection-sc-16frqer-1 iIZsGf&quot;]/div[@class=&quot;DropdownStyle__DropdownContainer-sc-1sc3c6h-1 fyNvNA aries-dropdown UserMenuComponentssc__Dropdown-sc-16frqer-2 UdYBy&quot;]/div[@class=&quot;DropdownStyle__DropdownWrapper-sc-1sc3c6h-0 boJQOp dropdown-contentwrapper&quot;]/ul[@class=&quot;DropdownStyle__DropdownBody-sc-1sc3c6h-3 iHjlAz dropdown-listbox&quot;]/li[@class=&quot;DropdownStyle__DropdownItemWrapper-sc-1sc3c6h-4 hRQwvs active&quot;]/div[@class=&quot;UserMenuComponentssc__DropdownWrapper-sc-16frqer-3 iHpuAM&quot;]/span[1]</value>
      <webElementGuid>2a3f3264-f8a3-42a9-a818-ea9a8f5cb1a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div[2]/div/div/div[4]/nav/div[5]/div[3]/div/div/div/div/ul/li[5]/div/span</value>
      <webElementGuid>65d0ed43-2ead-41de-a185-fc08837d897b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan Akun'])[1]/following::span[1]</value>
      <webElementGuid>f756acef-230b-4c4b-8bd3-f2737d3601d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiket Saya'])[1]/following::span[1]</value>
      <webElementGuid>a4e2198b-d0fa-4aad-85c6-855e7f26213e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/preceding::span[1]</value>
      <webElementGuid>527fb166-c677-4d60-8d50-c4ca5427ffb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>1509093e-afef-4295-b2a2-ba0d9e89f27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/span</value>
      <webElementGuid>af3ef5af-9ebc-4efe-8c38-bdca475756b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Keluar' or . = 'Keluar')]</value>
      <webElementGuid>fdb60a0a-f0f2-4c14-9bdb-d2b613cb43bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
