<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Masuk</name>
   <tag></tag>
   <elementGuidId>ae0fe53e-55eb-4c9e-a7a5-c7fef8ce889e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/div[2]/div/div/div[4]/nav/div[5]/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>45311260-00c9-47fe-bf07-690078c6cc5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>1ff01176-33ba-4edc-b00e-ab37f48b4320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;NavigationComponentssc__DrawerContainer-sc-vokz7d-0 daViyw&quot;]/div[@class=&quot;MainContainersc__MainLayout-sc-iy5ixg-0 llLQXs&quot;]/div[@class=&quot;MainContainersc__MainHeader-sc-iy5ixg-1 hiOHmW&quot;]/div[@class=&quot;GlintsContainer-sc-ap1z3q-0 iUnyrV max-height&quot;]/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-desktopS&quot;]/nav[@class=&quot;DesktopMenuComponentssc__Container-sc-wdt612-0 bFGUem&quot;]/div[@class=&quot;DesktopMenuComponentssc__RightMenuContainer-sc-wdt612-3 bSbWdk&quot;]/div[@class=&quot;DesktopMenuComponentssc__UserMenuItem-sc-wdt612-6 flfnAr&quot;]/div[@class=&quot;DesktopMenuComponentssc__Button-sc-wdt612-2 eHPzZH&quot;]/span[1]</value>
      <webElementGuid>6188fc0c-1d42-4cd5-b5cb-91c63bc65b72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/div[2]/div/div/div[4]/nav/div[5]/div[3]/div/span</value>
      <webElementGuid>abce028d-a1fc-4a72-983c-7aaabc48b715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::span[1]</value>
      <webElementGuid>405310a8-fecb-4f64-8701-34877ec65d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesian'])[1]/following::span[2]</value>
      <webElementGuid>c35d552f-0966-4a3b-874a-6d0948eb68af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='untuk perusahaan'])[1]/preceding::span[1]</value>
      <webElementGuid>52a923c0-1cca-42ee-b6ff-25d717aa2d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>1f0fcc4c-75fc-4dc4-a9a0-2816cb49fd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/span</value>
      <webElementGuid>73bb51e2-a444-4227-a769-a7ddebcefec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>c9f181a5-b19d-4534-913e-6fdc37a49028</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
